# run: docker-compose --file docker-compose.dev.yml up
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - APP_NAME=app1
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - APP_NAME=app2
    ports:
      - "5002:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.4.32
    container_name: barber-database-container
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./permissions.sql:/docker-entrypoint-initdb.d/permissions.sql
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DATABASE_HOST}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  redis:
    image: redis
    container_name: barber-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

volumes:
  mariadb-data:
  redis-data:
