name: Deploy

# Em qual situação quero que o pipeline rode
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

  # Assim podemos disparar também manualmente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Docker para autenticação
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login no Docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Configuração do Docker Compose passando as variáveis de ambiente
      - name: Run Docker Compose for Deployment
        run: |
          if [ "${GITHUB_REF_NAME}" == "develop" ]; then
            echo "Deploying to Development Environment"
            docker-compose -f docker-compose.yml up -d
          elif [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "Deploying to Production Environment"
            docker-compose -f docker-compose.yml up -d
          else
            echo "Unknown branch: ${GITHUB_REF_NAME}"
          fi
